version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:3000"  # Svelte frontend runs on 5173 locally but maps to 3000 inside the container
    environment:
      - PORT=3000    # Tell the frontend which port to use
    depends_on:
      - backend
      - sockets
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_TEST_URL=${DB_TEST_URL}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PROFILE=${PROFILE}
    networks:
      - app-network

  sockets:
    build:
      context: ./sockets
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose WebSocket backend on port 3000
    environment:
      - PORT=3000
    networks:
      - app-network

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"   # for apps to connect
        - "15672:15672" # management UI
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
      environment:
        RABBITMQ_DEFAULT_USER: devuser
        RABBITMQ_DEFAULT_PASS: devpass

volumes:
    rabbitmq_data:

networks:
  app-network:
    driver: bridge
