export const SECRETS = [
    // =========================
    // ZNÁMÁ RČENÍ
    // =========================

    {type: "Známé rčení", secret: "jeden o koze, druhý o voze"},
    {type: "Známé rčení", secret: "mít oči jako ostříž"},
    {type: "Známé rčení", secret: "jak si kdo ustele, tak si lehne"},
    {type: "Známé rčení", secret: "rozumět něčemu jako koza petrželi"},
    {type: "Známé rčení", secret: "házet flintu do žita"},
    {type: "Známé rčení", secret: "být v sedmém nebi"},
    {type: "Známé rčení", secret: "mít hluboko do kapsy"},
    {type: "Známé rčení", secret: "dělat z komára velblouda"},
    {type: "Známé rčení", secret: "mít máslo na hlavě"},
    {type: "Známé rčení", secret: "nosit dříví do lesa"},
    {type: "Známé rčení", secret: "kupovat zajíce v pytli"},
    {type: "Známé rčení", secret: "být páté kolo u vozu"},
    {type: "Známé rčení", secret: "mít za ušima"},
    {type: "Známé rčení", secret: "jít hlavou proti zdi"},
    {type: "Známé rčení", secret: "mít srdce na dlani"},
    {type: "Známé rčení", secret: "držet jazyk za zuby"},
    {type: "Známé rčení", secret: "strkat nos do cizích věcí"},
    {type: "Známé rčení", secret: "vzít nohy na ramena"},
    {type: "Známé rčení", secret: "mít hlavu v oblacích"},
    {type: "Známé rčení", secret: "co na srdci, to na jazyku"},
    {type: "Známé rčení", secret: "jablko nepadá daleko od stromu"},
    {type: "Známé rčení", secret: "oko za oko, zub za zub"},
    {type: "Známé rčení", secret: "kdo maže, ten jede"},
    {type: "Známé rčení", secret: "žádný učený z nebe nespadl"},
    {type: "Známé rčení", secret: "pro dobrotu na žebrotu"},
    {type: "Známé rčení", secret: "každý chvilku tahá pilku"},
    {type: "Známé rčení", secret: "dvě mouchy jednou ranou"},
    {type: "Známé rčení", secret: "být mezi dvěma ohni"},
    {type: "Známé rčení", secret: "jít s kůží na trh"},
    {type: "Známé rčení", secret: "mít za lubem"},
    {type: "Známé rčení", secret: "dělat mrtvého brouka"},
    {type: "Známé rčení", secret: "nechat někoho ve štychu"},
    {type: "Známé rčení", secret: "mít kliku"},
    {type: "Známé rčení", secret: "být v koncích"},
    {type: "Známé rčení", secret: "trefit hřebík na hlavičku"},
    {type: "Známé rčení", secret: "mít něco za lubem"},
    {type: "Známé rčení", secret: "být na koni"},
    {type: "Známé rčení", secret: "spadnout z višně"},
    {type: "Známé rčení", secret: "být z obliga"},
    {type: "Známé rčení", secret: "mít všech pět pohromadě"},
    {type: "Známé rčení", secret: "být vedle jak ta jedle"},
    {type: "Známé rčení", secret: "mít brouka v hlavě"},
    {type: "Známé rčení", secret: "chodit kolem horké kaše"},
    {type: "Známé rčení", secret: "strčit hlavu do písku"},
    {type: "Známé rčení", secret: "mít nervy na pochodu"},
    {type: "Známé rčení", secret: "přilévat olej do ohně"},
    {type: "Známé rčení", secret: "házet někomu klacky pod nohy"},
    {type: "Známé rčení", secret: "vytřít někomu zrak"},
    {type: "Známé rčení", secret: "nechat si zadní vrátka"},
    {type: "Známé rčení", secret: "být na štíru s něčím"},
    {type: "Známé rčení", secret: "mít něco v malíčku"},
    {type: "Známé rčení", secret: "mít plné zuby"},
    {type: "Známé rčení", secret: "přijít něčemu na kloub"},
    {type: "Známé rčení", secret: "jít z bláta do louže"},
    {type: "Známé rčení", secret: "být jako ryba ve vodě"},
    {type: "Známé rčení", secret: "být v jednom kole"},
    {type: "Známé rčení", secret: "to je jiná káva"},
    {type: "Známé rčení", secret: "mít zlaté ruce"},
    {type: "Známé rčení", secret: "mít obě ruce levé"},
    {type: "Známé rčení", secret: "být k nezaplacení"},
    {type: "Známé rčení", secret: "být trnem v oku"},
    {type: "Známé rčení", secret: "nechat někoho na holičkách"},
    {type: "Známé rčení", secret: "mít máslo na hlavě"},
    {type: "Známé rčení", secret: "mít hlavu jako pátrací balon"},
    {type: "Známé rčení", secret: "ztratit hlavu"},
    {type: "Známé rčení", secret: "mlátit prázdnou slámu"},
    {type: "Známé rčení", secret: "dělat z komára velblouda"},
    {type: "Známé rčení", secret: "být na vážkách"},
    {type: "Známé rčení", secret: "být pod pantoflem"},
    {type: "Známé rčení", secret: "mít něco na talíři"},
    {type: "Známé rčení", secret: "jít do tuhého"},
    {type: "Známé rčení", secret: "mít máslo na hlavě"},
    {type: "Známé rčení", secret: "pustit si někoho k tělu"},
    {type: "Známé rčení", secret: "mít z ostudy kabát"},
    {type: "Známé rčení", secret: "udělat kozla zahradníkem"},
    {type: "Známé rčení", secret: "mít štěstí v neštěstí"},
    {type: "Známé rčení", secret: "přijít s křížkem po funuse"},
    {type: "Známé rčení", secret: "být jako slon v porcelánu"},
    {type: "Známé rčení", secret: "chodit kolem horké kaše"},
    {type: "Známé rčení", secret: "mít něco pod palcem"},
    {type: "Známé rčení", secret: "nechat si věšet bulíky na nos"},
    {type: "Známé rčení", secret: "koukat jako vyoraná myš"},
    {type: "Známé rčení", secret: "být v tom až po uši"},
    {type: "Známé rčení", secret: "mít za lubem nějakou lumpárnu"},

    // =========================
    // PŘÍSLOVÍ
    // =========================

    {type: "Přísloví", secret: "Kdo jinému jámu kopá, sám do ní padá."},
    {type: "Přísloví", secret: "Kdo se směje naposled, ten se směje nejlépe."},
    {type: "Přísloví", secret: "Kdo pozdě chodí, sám sobě škodí."},
    {type: "Přísloví", secret: "Kdo šetří, má za tři."},
    {type: "Přísloví", secret: "Kdo hledá, najde."},
    {type: "Přísloví", secret: "Kdo chce kam, pomozme mu tam."},
    {type: "Přísloví", secret: "Kdo nic nedělá, nic nezkazí."},
    {type: "Přísloví", secret: "Ranní ptáče dál doskáče."},
    {type: "Přísloví", secret: "Tak dlouho se chodí se džbánem pro vodu, až se ucho utrhne."},
    {type: "Přísloví", secret: "Co můžeš udělat dnes, neodkládej na zítřek."},
    {type: "Přísloví", secret: "Jaký pán, takový krám."},
    {type: "Přísloví", secret: "Jaká matka, taková Katka."},
    {type: "Přísloví", secret: "V nouzi poznáš přítele."},
    {type: "Přísloví", secret: "S poctivostí nejdál dojdeš."},
    {type: "Přísloví", secret: "Lepší vrabec v hrsti než holub na střeše."},
    {type: "Přísloví", secret: "Dvakrát měř, jednou řež."},
    {type: "Přísloví", secret: "Čistota půl zdraví."},
    {type: "Přísloví", secret: "Trpělivost růže přináší."},
    {type: "Přísloví", secret: "Všude dobře, doma nejlépe."},
    {type: "Přísloví", secret: "Host do domu, Bůh do domu."},
    {type: "Přísloví", secret: "Jak zaseješ, tak sklidíš."},
    {type: "Přísloví", secret: "Kdo se bojí, nesmí do lesa."},
    {type: "Přísloví", secret: "Mluviti stříbro, mlčeti zlato."},
    {type: "Přísloví", secret: "Darovanému koni na zuby nehleď."},
    {type: "Přísloví", secret: "Líná huba, holé neštěstí."},
    {type: "Přísloví", secret: "Kdo dřív přijde, ten dřív mele."},
    {type: "Přísloví", secret: "Není všechno zlato, co se třpytí."},
    {type: "Přísloví", secret: "Dobrá rada nad zlato."},
    {type: "Přísloví", secret: "Čím výš vystoupíš, tím hlouběji padáš."},
    {type: "Přísloví", secret: "Kdo chce psa bít, hůl si vždycky najde."},
    {type: "Přísloví", secret: "Kdo uteče, vyhraje."},
    {type: "Přísloví", secret: "Kdo maže, ten jede."},
    {type: "Přísloví", secret: "Každý začátek je těžký."},
    {type: "Přísloví", secret: "Žádný učený z nebe nespadl."},
    {type: "Přísloví", secret: "Jak se do lesa volá, tak se z lesa ozývá."},
    {type: "Přísloví", secret: "Kdo jinému přeje, sám sobě přeje."},
    {type: "Přísloví", secret: "Kdo seje vítr, sklízí bouři."},
    {type: "Přísloví", secret: "Kdo má máslo na hlavě, ať nechodí na slunce."},
    {type: "Přísloví", secret: "Kovářova kobyla chodí bosa."},
    {type: "Přísloví", secret: "Pod svícnem bývá největší tma."},
    {type: "Přísloví", secret: "Ryba smrdí od hlavy."},
    {type: "Přísloví", secret: "Vrána k vráně sedá, rovný rovného si hledá."},
    {type: "Přísloví", secret: "Pes, který štěká, nekouše."},
    {type: "Přísloví", secret: "Kdo chce kam, pomozme mu tam."},
    {type: "Přísloví", secret: "Čas všechno zahojí."},
    {type: "Přísloví", secret: "Lepší pozdě než nikdy."},
    {type: "Přísloví", secret: "Lepší něco než nic."},
    {type: "Přísloví", secret: "Všechno zlé je pro něco dobré."},
    {type: "Přísloví", secret: "Není růže bez trní."},
    {type: "Přísloví", secret: "Kdo seje dobro, sklízí dobro."},
    {type: "Přísloví", secret: "Jaký otec, takový syn."},
    {type: "Přísloví", secret: "Co oči nevidí, to srdce nebolí."},
    {type: "Přísloví", secret: "Co je šeptem, to je s čertem."},
    {type: "Přísloví", secret: "Kdo chce psa bít, hůl si vždycky najde."},
    {type: "Přísloví", secret: "Komu není rady, tomu není pomoci."},
    {type: "Přísloví", secret: "Na každého jednou dojde."},
    {type: "Přísloví", secret: "Kdo se moc ptá, moc se dozví."},
    {type: "Přísloví", secret: "V jednoduchosti je síla."},
    {type: "Přísloví", secret: "Dobré slovo i železná vrata otevírá."},
    {type: "Přísloví", secret: "Kdo málo dává, málo dostává."},
    {type: "Přísloví", secret: "Kdo nepracuje, ať nejí."},
    {type: "Přísloví", secret: "Kde nic není, ani smrt nebere."},
    {type: "Přísloví", secret: "Kdo chce, hledá způsob. Kdo nechce, hledá důvod."},

    // =========================
    // PRANOSTIKY
    // =========================

    {type: "Pranostika", secret: "Březen, za kamna vlezem. Duben, ještě tam budem."},
    {type: "Pranostika", secret: "Medardova kápě, čtyřicet dní kape."},
    {type: "Pranostika", secret: "Svatá Anna, chladna zrána."},
    {type: "Pranostika", secret: "Na svatého Jiří vylézají hadi a štíři."},
    {type: "Pranostika", secret: "Studený máj, v stodole ráj."},
    {type: "Pranostika", secret: "Únor bílý, pole sílí."},
    {type: "Pranostika", secret: "Na Hromnice o hodinu více."},
    {type: "Pranostika", secret: "Jak na Nový rok, tak po celý rok."},
    {type: "Pranostika", secret: "Na svatého Václava babí léto nastává."},
    {type: "Pranostika", secret: "Svatý Martin přijíždí na bílém koni."},
    {type: "Pranostika", secret: "Kateřina na blátě, Vánoce na ledě."},
    {type: "Pranostika", secret: "Lucie noci upije, ale dne nepřidá."},
    {type: "Pranostika", secret: "Na Tři krále o krok dále."},
    {type: "Pranostika", secret: "Svatý Valentin sám je zazimován."},
    {type: "Pranostika", secret: "Je-li únor mírný ve své moci, duben pak se strojí k moci."},
    {type: "Pranostika", secret: "Březen bez vody, duben bez trávy."},
    {type: "Pranostika", secret: "Duben hojný vodou, říjen vínem."},
    {type: "Pranostika", secret: "Májová voda vypije víno."},
    {type: "Pranostika", secret: "Déšť na Medarda, mouka stračena."},
    {type: "Pranostika", secret: "Svatý Jan deštěm je znám."},
    {type: "Pranostika", secret: "Jak svatá Markéta přichází, tak se obilí do stodoly skládá."},
    {type: "Pranostika", secret: "Na svatého Prokopa promokne každá kopa."},
    {type: "Pranostika", secret: "Na svatého Jakuba brambor prvá úroda."},
    {type: "Pranostika", secret: "Svatý Vavřinec ukazuje, jaký podzim nastupuje."},
    {type: "Pranostika", secret: "Na Bartoloměje mraky v zemi naděje."},
    {type: "Pranostika", secret: "Na svatého Václava každá pláňka dozrává."},
    {type: "Pranostika", secret: "Svatý František zahání lidi do chýšek."},
    {type: "Pranostika", secret: "Na svatého Martina bývá dobrá peřina."},
    {type: "Pranostika", secret: "Svatá Kateřina strčí housle do komína."},
    {type: "Pranostika", secret: "Na svatého Mikuláše už je zima celá naše."},

    // =========================
    // SLAVNÉ CITÁTY
    // =========================

    {type: "Slavný citát", secret: "Buďte sami sebou; všichni ostatní jsou již obsazeni."},
    {type: "Slavný citát", secret: "Pouze dvě věci jsou nekonečné. Vesmír a lidská hloupost. U té první si tím však nejsem tak jist."},
    {type: "Slavný citát", secret: "Když něco opravdu chceš, celý vesmír se spojí, abys to mohl uskutečnit."},
    {type: "Slavný citát", secret: "Falešný přítel je horší než nepřítel, protože nepříteli se vyhýbáš, kdežto příteli věříš."},
    {type: "Slavný citát", secret: "Šťasten být neumíš, protože po tom, co nemáš, se ženeš, a co máš, na to zapomínáš."},
    {type: "Slavný citát", secret: "Život je to, co se stane, když jsme zaneprázdněni plánováním něčeho jiného."},
    {type: "Slavný citát", secret: "Fantazie je důležitější než vědomosti. Vědomosti jsou omezené, zatímco fantazie obsáhne celý svět."},
    {type: "Slavný citát", secret: "Kdo má proč žít, snese téměř jakékoli jak."},
    {type: "Slavný citát", secret: "Co tě nezabije, to tě posílí."},
    {type: "Slavný citát", secret: "Největší slávou v životě není nikdy nepadnout, ale pokaždé znovu vstát."},
    {type: "Slavný citát", secret: "I cesta dlouhá tisíc mil začíná prvním krokem."},
    {type: "Slavný citát", secret: "Žádný člověk není ostrov, úplný sám o sobě."},
    {type: "Slavný citát", secret: "Být či nebýt, to je otázka."},
    {type: "Slavný citát", secret: "Vím, že nic nevím."},
    {type: "Slavný citát", secret: "Myslím, tedy jsem."},
    {type: "Slavný citát", secret: "Vím, že nic nevím, ale v tom je má moudrost."},
    {type: "Slavný citát", secret: "Kdo chce změnit svět, musí nejprve změnit sám sebe."},
    {type: "Slavný citát", secret: "Štěstí přeje připraveným."},
    {type: "Slavný citát", secret: "Čas jsou peníze."},
    {type: "Slavný citát", secret: "V jednoduchosti je krása."},
    {type: "Slavný citát", secret: "Nikdy není pozdě stát se tím, kým bys mohl být."},
    {type: "Slavný citát", secret: "Každý začátek je těžký."},
    {type: "Slavný citát", secret: "Naděje umírá poslední."},
    {type: "Slavný citát", secret: "Člověk je tak starý, na kolik se cítí."},
    {type: "Slavný citát", secret: "Nezáleží na tom, jak pomalu jdeš, pokud se nezastavíš."},
    {type: "Slavný citát", secret: "Úspěch je součet malých snah opakovaných den za dnem."},
    {type: "Slavný citát", secret: "Nejlepší způsob, jak předpovědět budoucnost, je vytvořit ji."},
    {type: "Slavný citát", secret: "Každý génius má v sobě trochu šílenství."},
    {type: "Slavný citát", secret: "Člověk míní, život mění."},
    {type: "Slavný citát", secret: "Život není problém, který je třeba vyřešit, ale skutečnost, kterou je třeba prožít."},
    {type: "Slavný citát", secret: "Není důležité, co se ti stane, ale jak na to zareaguješ."},
    {type: "Slavný citát", secret: "Největší chyba je bát se udělat chybu."},
    {type: "Slavný citát", secret: "Když chceš zapalovat, musíš sám hořet."},
    {type: "Slavný citát", secret: "Člověk bez úsměvu by neměl otvírat obchod."},
    {type: "Slavný citát", secret: "Kdo chce psa bít, hůl si vždycky najde."},
    {type: "Slavný citát", secret: "Láska je slepá."},
    {type: "Slavný citát", secret: "Krása je v očích toho, kdo se dívá."},
    {type: "Slavný citát", secret: "Člověk se učí celý život."},
    {type: "Slavný citát", secret: "Moudrý člověk se učí z chyb druhých, hlupák ze svých."},
    {type: "Slavný citát", secret: "Odvaha není nepřítomnost strachu, ale vítězství nad ním."},
    {type: "Slavný citát", secret: "Největší vítězství je vítězství nad sebou samým."},
    {type: "Slavný citát", secret: "Kdo nikdy neudělal chybu, nikdy nezkusil nic nového."},
    {type: "Slavný citát", secret: "Člověk je tím, co ze sebe udělá."},
    {type: "Slavný citát", secret: "Čas je nejlepší lékař."},
    {type: "Slavný citát", secret: "Trpělivost je umění doufat."},
    {type: "Slavný citát", secret: "Přítel je ten, kdo o vás ví všechno a přesto vás má rád."},
    {type: "Slavný citát", secret: "Nejlepší přátelé jsou jako hvězdy. Ne vždy je vidíš, ale víš, že tu jsou."},
    {type: "Slavný citát", secret: "Domov není místo, kde bydlíš, ale místo, kde ti rozumějí."},
    {type: "Slavný citát", secret: "Kdo se směje, žije déle."},
    {type: "Slavný citát", secret: "Smích je nejkratší vzdálenost mezi dvěma lidmi."},
    {type: "Slavný citát", secret: "Život je krátký, ale umění dlouhé."},
    {type: "Slavný citát", secret: "Člověk není nikdy příliš starý na to, aby si stanovil nový cíl nebo snil nový sen."},
    {type: "Slavný citát", secret: "Nejlepší věci v životě nejsou věci."},
    {type: "Slavný citát", secret: "Kdo se bojí smrti, nemůže se radovat ze života."},
    {type: "Slavný citát", secret: "Náš život je takový, jakým ho činí naše myšlenky."},
    {type: "Slavný citát", secret: "Štěstí není něco hotového. Pochází z tvých vlastních činů."},
    {type: "Slavný citát", secret: "Každý den je nový začátek."},
    {type: "Slavný citát", secret: "To, co hledáš, hledá tebe."},
    {type: "Slavný citát", secret: "Tam, kde je láska, tam je život."},
    {type: "Slavný citát", secret: "Mír začíná úsměvem."},
    {type: "Slavný citát", secret: "Nikdo nemůže změnit člověka, který se nechce změnit."},
    {type: "Slavný citát", secret: "Kdo chce být šťastný, musí být ochoten být šťastný."},
    {type: "Slavný citát", secret: "Největší bohatství je zdraví a největší chudoba je nespokojenost."},
    {type: "Slavný citát", secret: "Kdo má odvahu žít, má odvahu zemřít."},
    {type: "Slavný citát", secret: "Všechno, co si dokážeš představit, je skutečné."},
    {type: "Slavný citát", secret: "Umění žít spočívá v tom vědět, jak málo je třeba k životu."},
    {type: "Slavný citát", secret: "Člověk je odsouzen být svobodný."},
    {type: "Slavný citát", secret: "Svoboda znamená odpovědnost. Proto se jí většina lidí bojí."},
    {type: "Slavný citát", secret: "Když se jedny dveře zavřou, jiné se otevřou."},
    {type: "Slavný citát", secret: "Budoucnost patří těm, kteří věří v krásu svých snů."},
    {type: "Slavný citát", secret: "Život je jako jízda na kole. Abyste udrželi rovnováhu, musíte se pohybovat."},
    {type: "Slavný citát", secret: "Někdy je třeba změnit sebe, ne svět kolem sebe."},
    {type: "Slavný citát", secret: "Nejlepší čas zasadit strom byl před dvaceti lety. Druhý nejlepší čas je právě teď."},
    {type: "Slavný citát", secret: "Člověk vidí správně pouze srdcem. Co je důležité, je očím neviditelné."},
    {type: "Slavný citát", secret: "Všichni dospělí byli nejprve dětmi, ale málokdo si to pamatuje."},
    {type: "Slavný citát", secret: "Stáváš se navždy zodpovědným za to, cos k sobě připoutal."},
    {type: "Slavný citát", secret: "Správně vidíme jen srdcem."},
    {type: "Slavný citát", secret: "Člověk riskuje, že bude trochu plakat, když se nechá ochočit."},
    {type: "Slavný citát", secret: "Lidé mají čas poznávat věci jen tak, že je kupují hotové u obchodníků."},
    {type: "Slavný citát", secret: "Je mnohem těžší soudit sebe než svého bližního."},
    {type: "Slavný citát", secret: "Člověk se vystavuje riziku, že bude plakat, když se nechá ochočit."},
    {type: "Slavný citát", secret: "Všechny velké věci jsou jednoduché a mnohé lze vyjádřit jediným slovem."},
    {type: "Slavný citát", secret: "Když chceš mít přítele, ochoč si mě."},
    {type: "Slavný citát", secret: "Člověk je bohatý tím, co dokáže postrádat."},
    {type: "Slavný citát", secret: "Není třeba být velkým, abys začal, ale musíš začít, abys byl velkým."},
    {type: "Slavný citát", secret: "Největší nebezpečí pro většinu z nás není, že náš cíl je příliš vysoký a my ho nedosáhneme, ale že je příliš nízký a my ho dosáhneme."},
    {type: "Slavný citát", secret: "Kvalita není nikdy náhoda. Je výsledkem inteligentního úsilí."},
    {type: "Slavný citát", secret: "Úspěch není konečný, neúspěch není osudný. Důležitá je odvaha pokračovat."},
    {type: "Slavný citát", secret: "Pokud procházíš peklem, pokračuj."},
    {type: "Slavný citát", secret: "Není důležité vyhrát, ale nikdy se nevzdat."},
    {type: "Slavný citát", secret: "Někdy se vítězství rodí z vytrvalosti, nikoli z talentu."},
    {type: "Slavný citát", secret: "Věř, že můžeš, a jsi na půl cesty."},
    {type: "Slavný citát", secret: "Začni tam, kde jsi. Použij to, co máš. Udělej, co můžeš."},
    {type: "Slavný citát", secret: "Nečekej na příležitost. Vytvoř ji."},
    {type: "Slavný citát", secret: "Život se neměří počtem nádechů, ale okamžiky, které nám vyrazí dech."},
    {type: "Slavný citát", secret: "Nejkrásnější věci v životě nelze vidět ani se jich dotknout. Musí se cítit srdcem."},
    {type: "Slavný citát", secret: "Člověk musí vědět, co chce, aby dokázal něco velkého."},
    {type: "Slavný citát", secret: "Když něco chceš, musíš pro to něco udělat."},
    {type: "Slavný citát", secret: "Každý problém má ve svém středu řešení."},
    {type: "Slavný citát", secret: "Největší překážkou na cestě k úspěchu je strach ze selhání."},
    {type: "Slavný citát", secret: "Někdy právě ty nejtěžší cesty vedou k nejkrásnějším místům."},
    {type: "Slavný citát", secret: "Kdo se nikdy nevzdává, nemůže být poražen."},
    {type: "Slavný citát", secret: "Není hanba spadnout. Hanba je zůstat ležet."},
    {type: "Slavný citát", secret: "Odvaha začíná tam, kde končí pohodlí."},
    {type: "Slavný citát", secret: "Člověk potřebuje ve svém životě něco, pro co stojí za to žít."},
    {type: "Slavný citát", secret: "Když nevíš, kam jdeš, žádná cesta není ta správná."},
    {type: "Slavný citát", secret: "Není možné vrátit se zpět a změnit začátek, ale můžeš začít tam, kde právě jsi, a změnit konec."},
    {type: "Slavný citát", secret: "Nezáleží na tom, kolikrát spadneš, ale kolikrát se zvedneš."},
    {type: "Slavný citát", secret: "Nejlepší okamžik pro začátek je právě teď."},
    {type: "Slavný citát", secret: "Kdo má sen, má důvod vstát z postele."},
    {type: "Slavný citát", secret: "Každý den udělej něco, čeho se bojíš."},
    {type: "Slavný citát", secret: "To, co děláš každý den, je důležitější než to, co uděláš jednou za čas."},
    {type: "Slavný citát", secret: "Štěstí není cíl, ale způsob života."},
    {type: "Slavný citát", secret: "Člověk může být šťastný jen tehdy, když přijme sám sebe."},
    {type: "Slavný citát", secret: "Žít znamená riskovat."},
    {type: "Slavný citát", secret: "Kdo se učí, zůstává mladý."},
    {type: "Slavný citát", secret: "Moudrost přichází s věkem, ale někdy věk přichází sám."},
    {type: "Slavný citát", secret: "Čím více člověk ví, tím více si uvědomuje, kolik toho neví."},
    {type: "Slavný citát", secret: "Největším nepřítelem poznání není nevědomost, ale iluze vědění."},
    {type: "Slavný citát", secret: "Kdo ovládá druhé, je mocný. Kdo ovládá sebe, je ještě mocnější."},
    {type: "Slavný citát", secret: "Nejlepší učitel je vlastní zkušenost."},
    {type: "Slavný citát", secret: "Chyby jsou důkazem, že se snažíš."},
    {type: "Slavný citát", secret: "Selhání je jen příležitost začít znovu, tentokrát chytřeji."},
    {type: "Slavný citát", secret: "Někdy musíš prohrát, abys zjistil, jak moc chceš vyhrát."},
    {type: "Slavný citát", secret: "Vítězství není všechno, ale chtít vyhrát ano."},
    {type: "Slavný citát", secret: "Když nemůžeš změnit situaci, změň svůj postoj k ní."},
    {type: "Slavný citát", secret: "To nejlepší teprve přijde."},
    {type: "Slavný citát", secret: "Minulost nezměníš, ale můžeš změnit to, co uděláš dnes."},
    {type: "Slavný citát", secret: "Budoucnost závisí na tom, co uděláš dnes."},
    {type: "Slavný citát", secret: "Člověk musí mít v sobě chaos, aby mohl zrodit tančící hvězdu."},
    {type: "Slavný citát", secret: "Bez hudby by byl život omylem."},
    {type: "Slavný citát", secret: "Život bez hudby by byl chybou."},
    {type: "Slavný citát", secret: "Hudba je vyšší zjevení než veškerá moudrost a filozofie."},
    {type: "Slavný citát", secret: "Kde slova selhávají, hudba mluví."},
    {type: "Slavný citát", secret: "Umění je lež, která nám umožňuje poznat pravdu."},
    {type: "Slavný citát", secret: "Každé dítě je umělec. Problém je, jak zůstat umělcem, když vyroste."},
    {type: "Slavný citát", secret: "Život napodobuje umění mnohem více než umění napodobuje život."},
    {type: "Slavný citát", secret: "Není nic horšího než obraz bez myšlenky."},
    {type: "Slavný citát", secret: "Kniha je nejtišší a nejstálejší přítel."},
    {type: "Slavný citát", secret: "Pokoj bez knih je jako tělo bez duše."},
    {type: "Slavný citát", secret: "Kdo čte, žije tisíc životů. Kdo nikdy nečte, žije jen jeden."},
    {type: "Slavný citát", secret: "Dobrá kniha je nejlepší přítel."},
    {type: "Slavný citát", secret: "Čtení je pro mysl tím, čím je cvičení pro tělo."},
    {type: "Slavný citát", secret: "Největší dobro, které můžeme udělat druhému, je nejen sdílet s ním své bohatství, ale ukázat mu jeho vlastní."},
    {type: "Slavný citát", secret: "Nikdy nepochybuj, že malá skupina přemýšlivých a odhodlaných lidí může změnit svět."},
    {type: "Slavný citát", secret: "Buď změnou, kterou chceš vidět ve světě."},
    {type: "Slavný citát", secret: "Oko za oko a celý svět bude slepý."},
    {type: "Slavný citát", secret: "Síla nespočívá v tom nikdy nepadnout, ale v tom vždy znovu povstat."},
    {type: "Slavný citát", secret: "Když ztratíš peníze, nic jsi neztratil. Když ztratíš zdraví, něco jsi ztratil. Když ztratíš charakter, ztratil jsi všechno."},
    {type: "Slavný citát", secret: "Vždy se zdá nemožné, dokud to není hotové."},
    {type: "Slavný citát", secret: "Není cesty k míru. Mír je cesta."},
    {type: "Slavný citát", secret: "Mír nelze udržet silou. Lze ho dosáhnout pouze porozuměním."},
    {type: "Slavný citát", secret: "Kdo chce mír, musí připravovat mír."},
    {type: "Slavný citát", secret: "Největší slávou není nikdy nepadnout, ale zvednout se pokaždé, když padneme."},
    {type: "Slavný citát", secret: "Není důležité, co máme, ale co s tím dokážeme udělat."},
    {type: "Slavný citát", secret: "Člověk potřebuje velmi málo, aby byl šťastný, ale velmi mnoho, aby byl spokojený."},
    {type: "Slavný citát", secret: "Kdo chce něco dokázat, hledá cestu. Kdo nechce, hledá výmluvu."},
    {type: "Slavný citát", secret: "Nikdy se nevzdávej toho, na co myslíš každý den."},
    {type: "Slavný citát", secret: "Každý den je nová příležitost změnit svůj život."},
    {type: "Slavný citát", secret: "Největší dobrodružství, které můžeš podniknout, je žít život svých snů."},
    {type: "Slavný citát", secret: "Život není o čekání, až bouře přejde. Je o tom naučit se tančit v dešti."},
    {type: "Slavný citát", secret: "Někdy je nejodvážnější věcí jednoduše pokračovat."},
    {type: "Slavný citát", secret: "Když se díváš příliš dlouho do minulosti, nevidíš cestu před sebou."},
    {type: "Slavný citát", secret: "Každá zkušenost, dobrá i špatná, nás někam posouvá."},
    {type: "Slavný citát", secret: "Život je příliš krátký na to, abychom ho žili podle představ někoho jiného."},
    {type: "Slavný citát", secret: "Neboj se pomalého růstu, boj se pouze toho, že zůstaneš stát."},
    {type: "Slavný citát", secret: "Největší vítězství je překonat člověka, kterým jsi byl včera."},
    {type: "Slavný citát", secret: "Kdo má trpělivost, má všechno."},
    {type: "Slavný citát", secret: "Když něco stojí za to, stojí za to to udělat dobře."},
    {type: "Slavný citát", secret: "Člověk může udělat chybu, ale nesmí se stát její obětí."},
    {type: "Slavný citát", secret: "Nejlepší způsob, jak se připravit na zítřek, je udělat maximum dnes."},
    {type: "Slavný citát", secret: "Každý problém je příležitost naučit se něco nového."},
    {type: "Slavný citát", secret: "Když nevíš, co dělat, udělej další správnou věc."},
    {type: "Slavný citát", secret: "Není důležité, odkud přicházíš, ale kam směřuješ."},
    {type: "Slavný citát", secret: "Nečekej, až budeš připraven. Začni a připravíš se cestou."},
    {type: "Slavný citát", secret: "Člověk se nestává silným tím, že se vyhýbá problémům, ale tím, že je překonává."},
    {type: "Slavný citát", secret: "Kdo dokáže ovládnout své emoce, dokáže ovládnout svůj život."},
    {type: "Slavný citát", secret: "Někdy největší vítězství spočívá v tom, že se odmítneš vzdát."},
    {type: "Slavný citát", secret: "To, co dnes vypadá jako konec, může být zítra nový začátek."},
    {type: "Slavný citát", secret: "Člověk potřebuje překážky, aby objevil svou sílu."},
    {type: "Slavný citát", secret: "Když cesta neexistuje, vytvoř ji."},
    {type: "Slavný citát", secret: "Největší omezení jsou často ta, která si vytvoříme sami."},
    {type: "Slavný citát", secret: "Není důležité mít všechno, ale umět si vážit toho, co máme."},
    {type: "Slavný citát", secret: "Štěstí je skutečné pouze tehdy, když se o něj dělíš."},
    {type: "Slavný citát", secret: "Člověk nikdy neví, jak silný je, dokud být silným není jedinou možností."},
    {type: "Slavný citát", secret: "Když pomůžeš jednomu člověku, změnil jsi svět k lepšímu."},
    {type: "Slavný citát", secret: "Laskavost nic nestojí a může znamenat všechno."},
    {type: "Slavný citát", secret: "Každý člověk, kterého potkáš, bojuje nějakou bitvu, o které nic nevíš."},
    {type: "Slavný citát", secret: "Buď laskavý, kdykoli je to možné. Vždy je to možné."},
    {type: "Slavný citát", secret: "Nejlepší věci v životě jsou lidé, které milujeme, místa, která navštívíme, a vzpomínky, které vytvoříme."},
    {type: "Slavný citát", secret: "Život je sbírka okamžiků. Udělej z nich něco krásného."},
    {type: "Slavný citát", secret: "Včerejšek je minulost, zítřek je budoucnost, ale dnešek je dar."},
    {type: "Slavný citát", secret: "Každý okamžik je nový začátek."},
    {type: "Slavný citát", secret: "Nejlepší čas být šťastný je právě teď."},
    {type: "Slavný citát", secret: "Žij každý den, jako by byl tvůj poslední."},
    {type: "Slavný citát", secret: "Člověk si často uvědomí hodnotu věcí až tehdy, když je ztratí."},
    {type: "Slavný citát", secret: "Někdy musíme něco ztratit, abychom pochopili, co pro nás znamenalo."},
    {type: "Slavný citát", secret: "Kdo se směje naposled, možná jen pomaleji pochopil vtip."},
    {type: "Slavný citát", secret: "Život je příliš krátký na to, abychom se zabývali maličkostmi."},
    {type: "Slavný citát", secret: "Není umění mít peníze, ale umět je používat."},
    {type: "Slavný citát", secret: "Bohatství nespočívá v tom, co vlastníš, ale v tom, bez čeho se dokážeš obejít."},
    {type: "Slavný citát", secret: "Člověk je bohatý podle počtu věcí, bez kterých se dokáže obejít."},
    {type: "Slavný citát", secret: "Kdo ovládá svůj jazyk, ovládá velkou část svého života."},
    {type: "Slavný citát", secret: "Někdy je mlčení tou nejlepší odpovědí."},
    {type: "Slavný citát", secret: "Slova mohou lhát, ale oči většinou ne."},
    {type: "Slavný citát", secret: "Pravda vítězí."},
    {type: "Slavný citát", secret: "Čas ukáže pravdu."},
    {type: "Slavný citát", secret: "Pravda může být někdy nepříjemná, ale vždy je lepší než lež."},
    {type: "Slavný citát", secret: "Kdo hledá pravdu, musí být připraven ji přijmout."},
    {type: "Slavný citát", secret: "Pravda nepotřebuje obhajobu."},
    {type: "Slavný citát", secret: "Lež má krátké nohy."},
    {type: "Slavný citát", secret: "Kdo jednou lže, tomu se těžko věří."},
    {type: "Slavný citát", secret: "Důvěra se buduje roky, ztrácí během okamžiku."},
    {type: "Slavný citát", secret: "Přátelství je jedna duše ve dvou tělech."},
    {type: "Slavný citát", secret: "Láska je nejsilnější ze všech vášní, protože útočí současně na hlavu, srdce i tělo."},
    {type: "Slavný citát", secret: "Milovat znamená nejen dívat se jeden na druhého, ale dívat se společně stejným směrem."},
    {type: "Slavný citát", secret: "Láska je jako vítr, nevidíš ji, ale cítíš ji."},
    {type: "Slavný citát", secret: "Kde je láska, tam je život."},
    {type: "Slavný citát", secret: "Láska neznamená dívat se jeden na druhého, ale dívat se společně stejným směrem."},
    {type: "Slavný citát", secret: "Kdo chce být milován, musí být ochoten milovat."},
    {type: "Slavný citát", secret: "Největší dar, který můžeš někomu dát, je tvůj čas."},
    {type: "Slavný citát", secret: "Čas strávený s rodinou není nikdy ztracený čas."},
    {type: "Slavný citát", secret: "Rodina není důležitá věc. Je to všechno."},
    {type: "Slavný citát", secret: "Domov je tam, kde začíná naše příběh."},
    {type: "Slavný citát", secret: "Člověk potřebuje kořeny, aby mohl růst."},
    {type: "Slavný citát", secret: "Největší dar rodičů dětem je jejich čas a pozornost."},
    {type: "Slavný citát", secret: "Děti jsou hosté, které musíme vychovat, aby jednou odešly."},
    {type: "Slavný citát", secret: "Moudrost není vědět všechno, ale vědět, co nevíš."},
    {type: "Slavný citát", secret: "Moudrost začíná úžasem."},
    {type: "Slavný citát", secret: "Poznání začíná otázkou."},
    {type: "Slavný citát", secret: "Otázka je polovina odpovědi."},
    {type: "Slavný citát", secret: "Kdo se ptá, je hlupák pět minut. Kdo se neptá, zůstane hlupákem navždy."},
    {type: "Slavný citát", secret: "Chytrý člověk se učí ze svých chyb, moudrý ze zkušeností druhých."},
    {type: "Slavný citát", secret: "Zkušenost je učitel, který přichází až po zkoušce."},
    {type: "Slavný citát", secret: "Člověk se učí nejlépe tehdy, když něco sám objeví."},
    {type: "Slavný citát", secret: "Kdo chce dosáhnout nemožného, musí nejprve zkusit nemožné."},
    {type: "Slavný citát", secret: "Neexistuje problém, který by nebyl menší, když se o něm podělíš."},
    {type: "Slavný citát", secret: "Velké věci vznikají z malých kroků."},
    {type: "Slavný citát", secret: "Vytrvalost je klíčem k úspěchu."},
    {type: "Slavný citát", secret: "Trpělivost a vytrvalost mají účinek jako dvě kapky vody na kámen."},
    {type: "Slavný citát", secret: "Kdo vydrží, ten vyhraje."},
    {type: "Slavný citát", secret: "Někdy je třeba jít proti proudu, abychom se dostali tam, kam chceme."},
    {type: "Slavný citát", secret: "Neboj se být jiný. Boj se být stejný jako všichni ostatní."},
    {type: "Slavný citát", secret: "Buď originál, ne kopie."},
    {type: "Slavný citát", secret: "Největší svoboda je být sám sebou."},
    {type: "Slavný citát", secret: "Člověk by měl být sám sebou, protože všichni ostatní už jsou zabraní."},
    {type: "Slavný citát", secret: "Neztrácej čas vysvětlováním. Lidé slyší jen to, co chtějí slyšet."},
    {type: "Slavný citát", secret: "Není třeba se zavděčit všem. Není to ani možné."},
    {type: "Slavný citát", secret: "Když se snažíš zavděčit všem, nakonec nezavděčíš nikomu."},
    {type: "Slavný citát", secret: "Největší vítězství je být spokojený sám se sebou."},
    {type: "Slavný citát", secret: "Sebevědomí není věřit, že jsi lepší než ostatní, ale vědět, že nemusíš být lepší než ostatní."},
    {type: "Slavný citát", secret: "Nemusíš být nejlepší. Stačí být lepší než včera."},
    {type: "Slavný citát", secret: "Srovnávej se pouze s člověkem, kterým jsi byl včera."},
    {type: "Slavný citát", secret: "Každý člověk má svůj vlastní příběh."},
    {type: "Slavný citát", secret: "Nikdy nevíš, jaký boj svádí člověk vedle tebe."},
    {type: "Slavný citát", secret: "Laskavost je jazyk, kterému rozumí i hluchý a který vidí i slepý."},
    {type: "Slavný citát", secret: "Malý čin laskavosti může změnit celý něčí den."},
    {type: "Slavný citát", secret: "Nikdy nepodceňuj sílu jednoho dobrého slova."},
    {type: "Slavný citát", secret: "Úsměv je nejlevnější způsob, jak změnit svůj vzhled."},
    {type: "Slavný citát", secret: "Smích prodlužuje život."},
    {type: "Slavný citát", secret: "Když se směješ, svět se směje s tebou."},
    {type: "Slavný citát", secret: "Radost není v tom, co máme, ale v tom, co dokážeme prožívat."},
    {type: "Slavný citát", secret: "Štěstí není stanice, do které přijedeš, ale způsob cestování."},
    {type: "Slavný citát", secret: "Člověk často hledá štěstí daleko od sebe, přestože ho má přímo před očima."},
    {type: "Slavný citát", secret: "Nečekej na šťastný okamžik. Udělej šťastný okamžik."},
    {type: "Slavný citát", secret: "Radost ze života spočívá v maličkostech."},
    {type: "Slavný citát", secret: "Kdo neumí být šťastný s málem, nebude šťastný ani s mnohým."},
    {type: "Slavný citát", secret: "Člověk má tolik štěstí, kolik si ho dokáže uvědomit."},
    {type: "Slavný citát", secret: "Nejkrásnější okamžiky jsou ty, které bychom si nejraději zopakovali."},
    {type: "Slavný citát", secret: "Vzpomínky jsou jediným rájem, ze kterého nás nikdo nemůže vyhnat."},
    {type: "Slavný citát", secret: "Některé okamžiky trvají sekundu, ale zůstanou v nás celý život."},
    {type: "Slavný citát", secret: "Čas, který věnujeme lidem, které milujeme, nikdy není ztracený."},
    {type: "Slavný citát", secret: "Nejlepší vzpomínky vznikají tehdy, když jsme přestali plánovat."},
    {type: "Slavný citát", secret: "Život je cesta, ne cíl."},
    {type: "Slavný citát", secret: "Nezáleží na cíli, ale na cestě, která k němu vede."},
    {type: "Slavný citát", secret: "Každá cesta začíná prvním krokem."},
    {type: "Slavný citát", secret: "Cesta je někdy důležitější než cíl."},
    {type: "Slavný citát", secret: "Kdo ví, kam jde, nepotřebuje spěchat."},
    {type: "Slavný citát", secret: "Někdy se musíš ztratit, abys našel správnou cestu."},
    {type: "Slavný citát", secret: "Nejkrásnější cesty jsou ty, které jsme neplánovali."},
    {type: "Slavný citát", secret: "Každá překážka je příležitostí naučit se něco nového."},
    {type: "Slavný citát", secret: "Překážky jsou ty strašidelné věci, které vidíš, když spustíš oči z cíle."},
    {type: "Slavný citát", secret: "Když se díváš na překážku, nevidíš cestu."},
    {type: "Slavný citát", secret: "Někdy je cesta nahoru těžká, ale výhled za to stojí."},
    {type: "Slavný citát", secret: "Člověk roste tím, co překonává."},
    {type: "Slavný citát", secret: "Obtížné cesty často vedou k krásným místům."},
    {type: "Slavný citát", secret: "Nejlepší výhled přichází po nejtěžším výstupu."},
    {type: "Slavný citát", secret: "Hory nás učí, že cesta nahoru začíná vždy prvním krokem."},
    {type: "Slavný citát", secret: "Kdo chce vystoupat vysoko, musí se nejprve naučit stoupat."},
    {type: "Slavný citát", secret: "Někdy musíš vylézt vysoko, abys viděl, jak malý byl problém dole."},
];
